#!/bin/sh -e

qemu-system-riscv64 \
    -M virt -m 2G -smp 1 -nographic \
    -bios gadget/prime/fw_payload.elf \
    -drive file=virt.img,format=raw,if=virtio \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-device,rng=rng0 \
    -device virtio-net-device,netdev=usernet \
    -netdev user,id=usernet,hostfwd=tcp::22222-:22
