name: uc-initrd
base: core20
version: '0'
version-script: echo "20-$(apt-cache search --names-only "linux-image-5.11.0.*-generic" | sort | tail -1 | awk -F '-' '{print $3"-"$4}')"
summary: Ubuntu Core initrd
description: |
  Ubuntu Core initrd

grade: stable
confinement: strict

parts:
    initrd:
        plugin: nil
        override-build: |
            # UC20 initrd builder only supports native build!
            # build UC20 initrd
            if [ -z "$(which ubuntu-core-initramfs)" ]; then
                sudo add-apt-repository -y ppa:snappy-dev/image
                sudo apt-get install -y ubuntu-core-initramfs
            fi
            # first prepare empty kernel modules structure. We want *vanilla* initrd anyway
            kernel_version="5.11.0"
            modules_path_release="lib/modules/${kernel_version}"
            mkdir -p ${modules_path_release}
            touch ${modules_path_release}/modules.builtin
            touch ${modules_path_release}/modules.order
            depmod -b . ${kernel_version}
            # we need to run tool as root to get rigt permissions
            mkdir -p clean-initrd
            sudo ubuntu-core-initramfs create-initrd \
                --kerneldir ${modules_path_release} \
                --kernelver ${kernel_version} \
                --output ${SNAPCRAFT_PART_INSTALL}/initrd
            sudo chown ${USER}:${USER} ${SNAPCRAFT_PART_INSTALL}/initrd*
        organize:
            "initrd-*": vanilla-initrd.img

    initrd-repack:
        plugin: nil
        after:
            - initrd
        override-build: |
            # remove any kernel modules added here
            unmkinitramfs ${SNAPCRAFT_STAGE}/vanilla-initrd.img .
            rm -rf usr/lib/modules/*
            find . | cpio --create --quiet --format='newc' --owner=0:0 | lz4 -l -7 > ${SNAPCRAFT_PART_INSTALL}/initrd.img

build-packages:
    - software-properties-common
    - initramfs-tools-core
