name: virt-kernel
adopt-info: kernel
build-base: core22
summary: A RISC-V 64-bit kernel for Qemu's virt board
description: This is a snapped kernel for an emulated RISC-V system.
type: kernel
architectures:
  - build-on:  [amd64, riscv64]
    build-for: [riscv64]
grade: stable
confinement: strict

package-repositories:
  - type: apt
    url: https://ppa.launchpadcontent.net/canonical-kernel-team/ppa/ubuntu
    suites: [jammy]
    components: [main]
    architectures: [riscv64]
    key-id: 110E21D8B0E2A1F0243AF6820856F197B892ACEA
    key-server: keyserver.ubuntu.com

parts:
  kernel:
    plugin: nil
    stage-packages:
      - linux-generic:${CRAFT_TARGET_ARCH}
    override-stage: |
      craftctl default
      craftctl set version=$(ls ${CRAFT_PART_INSTALL}/modules/ | cut -f1 -d/)
    stage:
      - -boot/
      - -etc/
      - -usr/
    organize:
      boot/vmlinuz-*: Image
      boot/config-*: kconfig
      lib/modules: modules/
      lib/firmware/regulatory.db*: firmware/
      usr/src/linux-headers-*/Module.symvers: Module.symvers
    prime:
      - -Image
      # Remove large modules that will never be used
      - -modules/*/kernel/drivers/gpu/drm/amd
      - -modules/*/kernel/drivers/gpu/drm/nouveau
      - -modules/*/kernel/drivers/gpu/drm/radeon
      - -modules/*/kernel/drivers/scsi
      - -modules/*/kernel/drivers/net/can
      - -modules/*/kernel/drivers/net/dsa
      - -modules/*/kernel/drivers/net/wireless/ath
      - -modules/*/kernel/drivers/net/wireless/intel
      - -modules/*/kernel/drivers/net/wireless/mediatek
      - -modules/*/kernel/drivers/net/wireless/broadcom
      - -modules/*/kernel/drivers/net/wireless/marvell
      - -modules/*/kernel/drivers/net/wireless/ralink
      - -modules/*/kernel/drivers/net/wireless/intersil
      - -modules/*/kernel/drivers/net/wireless/ti
      - -modules/*/kernel/drivers/infiniband
      - -modules/*/kernel/drivers/sound/pci
      - -modules/*/kernel/drivers/comedi

  initrd:
    after: [kernel]
    plugin: nil
    source: initrd
    build-packages:
      - lz4
      - kmod
    override-build: |
      KVER=5.15.0-1020-generic

      lz4cat uc-initrd_*_riscv64.img | cpio -idm
      rm -f uc-initrd_*_riscv64.img

      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko \
        lib/modules/${KVER}/kernel/fs/nls/nls_iso8859-1.ko
      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/fs/fuse/virtiofs.ko \
        lib/modules/${KVER}/kernel/fs/fuse/virtiofs.ko
      install -Dm644 ${CRAFT_STAGE}/modules/${KVER}/kernel/drivers/block/virtio_blk.ko \
        lib/modules/${KVER}/kernel/drivers/block/virtio_blk.ko

      depmod -avb . ${KVER}

      find . | cpio -o -H newc -R 0:0 | lz4 -9 -l > ${CRAFT_PART_INSTALL}/initrd.img
    prime:
      - -initrd.img

  firmware:
    plugin: nil
    stage-packages:
      - linux-firmware
    organize:
      lib/firmware: firmware/
    stage:
      - -usr
      - -lib
      # Remove large firmware files that will never be used
      - -firmware/amd
      - -firmware/amdgpu
      - -firmware/asihpi
      - -firmware/cavium
      - -firmware/cxgb3
      - -firmware/cxgb4
      - -firmware/dpaa2
      - -firmware/i915
      - -firmware/intel
      - -firmware/iwlwifi-*
      - -firmware/liquidio
      - -firmware/matrox
      - -firmware/mediatek
      - -firmware/mellanox
      - -firmware/mrvl
      - -firmware/moxa
      - -firmware/netronome
      - -firmware/nvidia
      - -firmware/qed
      - -firmware/radeon
      - -firmware/rockchip
      - -firmware/ath10k/QCA9377/hw1.0/firmware-5.bin
      - -firmware/ath3k-1.fw
      - -firmware/qca/htbtfw20.tlv
      - -firmware/qcom
      - -firmware/s5p*
      - -firmware/ath11k
      - -firmware/ath10k
      - -firmware/brcm
      - -firmware/vsc
      - -firmware/cypress

  dtb:
    plugin: nil
    build-packages:
      - qemu-system-misc
      - device-tree-compiler
    override-build: |
      qemu-system-${CRAFT_TARGET_ARCH} -machine virt -m 2G -smp 1 \
        -machine dumpdtb=${CRAFT_PART_INSTALL}/qemu.dtb
    prime:
      - -*

  fit-image:
    after:
      - kernel
      - initrd
      - dtb
    plugin: nil
    build-packages:
      - u-boot-tools
    source: fit-image
    override-build: |
      mkimage -f ${CRAFT_PART_BUILD}/fitImage-riscv64.its \
        ${CRAFT_PART_INSTALL}/kernel.img
